GOBLIN_HIT_BACK = true
GOBLINS_FALL = true
GOBLINS_CAN_SPAWN = true
VEIN_GOBLINS_CAN_SPAWN = true
GOBLIN_SPAWN_RATE = 20
VEIN_GOBLIN_SPAWN_RATE = 35
GOBLIN_SPAWN_RATE_D = 100
VEIN_GOBLIN_SPAWN_RATE_D = 1
GOBLIN_GROUP_SIZE = 2
VEIN_GOBLIN_GROUP_SIZE = 2
